baseURL = "https://apediderot.gitlab.io/"
languageCode = "fr-fr"
title = "APE - Diderot"
theme = "ape-bootstrap4"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    description = "Association des parents d'élèves de l'école Denis Diderot à Lille"
    githubUsername = "#"
    accent = "#721e77"
    showBorder = true
    # backgroundColor = "#eee"
    font = "Raleway" # should match the name on Google Fonts!
    profilePic = "/images/APE-Diderot.svg"
    copyright = "Créé avec [Hugo](https://gohugo.io)."
    # css = ["css/ape.css"]

[[menu.main]]
    url = "/"
    name = "Accueil"
    weight = 1

[[menu.main]]
    url = "/actu/"
    name = "Actualités"
    weight = 2

[[menu.main]]
    url = "/ape/"
    name = "APE"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:ape.diderot.lille@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/apediderot"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/apediderot"
    name = "twitter"
    weight = 3
